version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: circleci/ruby
    versions:
    - 3.0.0.pre.node
